<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Huawei-PC" failures="1" tests="1" name="Case_12" time="15.795" errors="0" timestamp="2022-09-30T17:56:32 EEST">
  <testcase classname="AuthorizationCase_12" name="case_12" time="15.795">
    <failure type="java.lang.AssertionError" message="expected [https://coinzix.com/login] but found [https://coinzix.com/sign-up]">
      <![CDATA[java.lang.AssertionError: expected [https://coinzix.com/login] but found [https://coinzix.com/sign-up]
at AuthorizationCase_12.case_12(AuthorizationCase_12.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- case_12 -->
</testsuite> <!-- Case_12 -->
